### ISSUE TITLE
师傅报错这个咋解决呀

### ISSUE THREAD

**Issue by centkali** [Wker666/Demo#18]
![image](https://user-images.githubusercontent.com/87803292/160038717-1ce13f3e-c807-410f-9765-d03bc2994a13.png)

**Comment by Wker666** [comment]
这个脚本的代码是什么？

**Comment by centkali** [comment]
通达OAgetshell的那个

**Comment by centkali** [comment]
![image](https://user-images.githubusercontent.com/87803292/160039387-c67d6d39-a860-479a-84c3-b8b8aa64b319.png)

**Comment by Wker666** [comment]
那个应该是你没下载完全代码，里面有个shell包

**Comment by centkali** [comment]
![image](https://user-images.githubusercontent.com/87803292/160039543-7e097d87-0f34-48c1-9d59-c843092f0006.png)

**Comment by centkali** [comment]
这个是师傅吗

**Comment by Wker666** [comment]
嗯嗯
